### ISSUE TITLE
Error when installing in PW 3

### ISSUE THREAD

**Issue by tobaco** [justb3a/processwire-importpagesxml#1]
When i try to install this module in Processwire 3 i get the following error message:

> Error: Call to undefined function Jos\Lib\wire() (Line 34 in /Users/…/site/modules/ImportPagesXml/lib/Parser.php) 

if i add the `\ProcessWire\` namespace by hand it seems to work.
seems like the filecompiler doesn't catch the files in the lib folder.

**Comment by justb3a** [comment]
Hi,
ImportPagesXML is not yet ready for PW 3.X, I had no time to test it so far. Thanks for the report, I'll test it soon.

**Comment by tobaco** [comment]
ok, thanks!

**Comment by justb3a** [comment]
Branch **develop** supports PW3.
