### ISSUE TITLE
Can't import from Xml

### ISSUE THREAD

**Issue by Manaus** [justb3a/processwire-importpagesxml#3]
Hello, 
This is a xml file example...   

```
<root>
  <article id="245">  
    <title>Video e&#160;Condivisone</title>
    <body>  <p>Video e Condivisone</p>
        <p><strong>Ingresso gratuito</strong></p></body>
    <data_evento>2015-11-11</data_evento>
    <luogo_evento>Associazione</luogo_evento>
    <partecipazione></partecipazione>
    <categoria_uno>video</categoria_uno>
    <categoria_due></categoria_due>
    <immagine></immagine>
  </article>
  <article ... >
</root>
```

I set the context to `//article`, the title to `title`, the body to `body` and so on. Yet always I get a 0 pages created, without error. What am I doing wrong? 

Thanks!

**Comment by justb3a** [comment]
Hi,

I tested it using your setup and everything works fine. The only thing I noticed, you have to wrap the content inside the `body` tag in `<![CDATA[]]>`, if you want to import the embedded content as html.

``` xml
    <body><![CDATA[<p>Video e Condivisone</p>
        <p><strong>Ingresso gratuito</strong></p>]]></body>
```

Without doing this the pages will be created as well, but the field in which you want to import the content of the body tag, keeps empty.

Could you please compare your setup:

![screen shot 2016-03-22 at 08 41 01](https://cloud.githubusercontent.com/assets/4669205/13944989/2b02f6b8-f00a-11e5-82b7-fef14bd6510b.png)
![screen shot 2016-03-22 at 08 41 44](https://cloud.githubusercontent.com/assets/4669205/13944997/36798246-f00a-11e5-942b-61fbad8713f1.png)

**Comment by Manaus** [comment]
Thanks @justonestep, I tried out your fine tuning, but still I get 0 pages created... Maybe I should try with fewer values, at the moment I am trying to create 200 pages. 
Btw I cannot remove the Path to images value, if I save a blank field, I get back the previous one.

**Comment by Manaus** [comment]
@justonestep Tried with a single `article` node, not succeded. My version is 2.7.2 with plugin version 0.0.3...

**Comment by justb3a** [comment]
I set up a fresh PW2.7.2 installation and also used ImportPagesXML version 0.0.3. Here is my test xml-file:

``` xml
<root>
  <article id="245">
    <title>Video e&#160;Condivisone</title>
    <body><![CDATA[<p>Video e Condivisone</p>
        <p><strong>Ingresso gratuito</strong></p>]]></body>
    <data_evento>2015-11-11</data_evento>
    <luogo_evento>Associazione</luogo_evento>
    <partecipazione></partecipazione>
    <categoria_uno>video</categoria_uno>
    <categoria_due></categoria_due>
    <immagine></immagine>
  </article>
  <article id="345">
    <title>Video2 e&#160;Condivisone</title>
    <body><![CDATA[<p>Vide2o e Condivisone</p>
        <p><strong>Ingresso gratuito</strong></p>]]></body>
    <data_evento>2015-11-11</data_evento>
    <luogo_evento>Associazione</luogo_evento>
    <partecipazione></partecipazione>
    <categoria_uno>video</categoria_uno>
    <categoria_due></categoria_due>
    <immagine></immagine>
  </article>
</root>
```

Could you please test with the same setup as I did? There must be a difference! Please attach a screenshot of your setup, maybe I can find the difference.

**Comment by Manaus** [comment]
Hi @justonestep, 
I tried with your xml file, and that's the one in the screenshot. The setup looks quite similar. 
The parent file, XmlTest, is a basic-page template, and there are no restriction on the Family for creating new pages and so on. 

Thanks

![screenshot at mar 24 17-09-58](https://cloud.githubusercontent.com/assets/1131505/14023179/783eb6f8-f1e3-11e5-8d96-f7cc46b0e620.png)

**Comment by Manaus** [comment]
I'm attaching a video of the procedure
https://cloudup.com/cWJA3NHzu0i

**Comment by justb3a** [comment]
Any news on this? Unfortunately I have no clue why it's not working for you. Did you check the encoding of the file (should be utf8). I close this for now.
